name: Build and push

on:
  push:
    branches: [main]

jobs:
  build-push-images:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: cache docker cache
        uses: actions/cache@v1
        with: 
          path: ${{ github.workspace }}/cache
          key: ${{ runner.os }}-docker-${{ hashfiles('cache/**') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          cache-from: type=local,src=$GITHUB_WORKSPACE/cache
          cache-to: type=local,dest=$GITHUB_WORKSPACE/cache
          platforms: "linux/arm/v7,linux/arm64/v8,linux/amd64"
          tags: |
            maciogx2/pfswco_1
